### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function Spatie\ImageOptimizer\mime_content_type()

### ISSUE THREAD

**Issue by sonnetmia** [TypistTech/image-optimize-command#31]
I am trying to use this package into wp-cli. When I try to optimize images, I am getting this error. 

Fatal error: Uncaught Error: Call to undefined function Spatie\ImageOptimizer\mime_content_type() in /home/xxx/.wp-cli/packages/vendor/spatie/image-optimizer/src/Image.php:22
Stack trace:
#0 /home/xxx/.wp-cli/packages/vendor/spatie/image-optimizer/src/Optimizers/Jpegoptim.php(13): Spatie\ImageOptimizer\Image->mime()
#1 /home/xxx/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php(83): Spatie\ImageOptimizer\Optimizers\Jpegoptim->canHandle(Object(Spatie\ImageOptimizer\Image))
#2 /home/xxx/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Jpegoptim), Object(Spatie\ImageOptimizer\Image))
#3 /home/xxx/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(73): Spatie\ImageOptimizer\OptimizerChain->optimize('/home/xxx/...')
#4 [internal function]: TypistTech\ImageOptimizeCommand\Operations\Optimize->TypistTech\ImageOptimizeCommand\Ope in /home/xxx/.wp-cli/packages/vendor/spatie/image-optimizer/src/Image.php on line 22

is there anything missing during installation? 
My command is:: 
wp image-optimize find /home/xxx/public_html  --extensions=gif,jpeg,jpg,png,svg

Thanks in advance.

**Comment by TangRufus** [comment]
Let's see how https://github.com/spatie/image-optimizer/issues/76 works out.

**Comment by sonnetmia** [comment]
Just configured php fileinfo extension. Looks like it's working now.

**Comment by amustci065** [comment]
How did you configure the fileinfo extension?

**Comment by TangRufus** [comment]
Depends on your server.

See answers here: https://stackoverflow.com/questions/3579072/php-fileinfo-is-undefined-function/
