### ISSUE TITLE
undefined method fromShellCommandline

### ISSUE THREAD

**Issue by Jerome38** [TypistTech/image-optimize-command#35]
Hello,

First of all, thx for this extension that looks awesome.
I have an issue when i try using it and i hope you will be able to help me

> wp image-optimize batch

===> Backing up full sized images for 10 attachment(s)
===> Backing up 10 full sized image(s)
Finished
===> Optimizing images for 10 attachment(s)
===> Optimizing images of attachment ID: 9714
===> Optimizing 6 file(s)
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /home/forge/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php:97
Stack trace:
#0 /home/forge/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Jpegoptim), Object(Spatie\ImageOptimizer\Image))
#1 /home/forge/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(73): Spatie\ImageOptimizer\OptimizerChain->optimize('/home/forge/mon...')
#2 [internal function]: TypistTech\ImageOptimizeCommand\Operations\Optimize->TypistTech\ImageOptimizeCommand\Operations\{closure}('/home/forge/mon...')
#3 /home/forge/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(74): array_map(Object(Closure), Array)
#4 /home/forge/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/AttachmentImages/Optimize.php(104): T in /home/forge/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php on line 97

Any idea what i did wrong ?

Thx

**Comment by TangRufus** [comment]
Seems related to https://github.com/spatie/image-optimizer/commit/83cbef0969df3b6788520aa0d3a3685d83b8bfd0#diff-b00ecbef43b571343ac6639739b14f72

Please try:
A) update `symfony/process`, OR
B) install an older version of `spatie/image-optimizer`

**Comment by Jerome38** [comment]
It's working after downgrade spatie/image-optimizer

thx

**Comment by TangRufus** [comment]
I was wrong, see: #37. Sorry.
Continue on #37
