### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process

### ISSUE THREAD

**Issue by opicron** [TypistTech/image-optimize-command#37]
First of all, thank you for this great WP CLI script. Really hope to get it running on our system. Running the following command:

`wp image-optimize attachment 12660 --allow-root`

On this machine:

```
Ubuntu 18.04.1 LTS
PHP 7.2.15-0

```

Which results in this error:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\Process::fromShellCommandline() in /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php:97
Stack trace:
#0 /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php(77): Spatie\ImageOptimizer\OptimizerChain->applyOptimizer(Object(Spatie\ImageOptimizer\Optimizers\Jpegoptim), Object(Spatie\ImageOptimizer\Image))
#1 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(73): Spatie\ImageOptimizer\OptimizerChain->optimize('/var/www/html/w...')
#2 [internal function]: TypistTech\ImageOptimizeCommand\Operations\Optimize->TypistTech\ImageOptimizeCommand\Operations\{closure}('/var/www/html/w...')
#3 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/Optimize.php(74): array_map(Object(Closure), Array)
#4 /root/.wp-cli/packages/vendor/typisttech/image-optimize-command/src/Operations/AttachmentImages/Optimize.php(104): TypistTech\ImageOptimizeCommand in /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php on line 97

```

The install went as following:

```
wp package install typisttech/image-optimize-command:@stable --allow-root
Installing package typisttech/image-optimize-command (@stable)
Updating /root/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #1)

Dependency resolution completed in 5.266 seconds
Analyzed 6338 packages to resolve dependencies
Analyzed 542383 rules to resolve dependencies
Package operations: 7 installs, 0 updates, 0 removals
Installs: symfony/finder:v4.2.3, symfony/polyfill-ctype:v1.10.0, symfony/filesystem:v4.2.3, symfony/process:v4.2.3, psr/log:1.1.0, spatie/image-optimizer:1.1.5, typisttech/image-optimize-command:0.3.1
 - Installing symfony/finder (v4.2.3)
 - Warning: typisttech/image-optimize-command 0.3.1 requires symfony/finder ^4.1 -> satisfiable by symfony/finder[4.1.x-dev, 4.2.x-dev, 4.3.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.2, v4.2.3].
 - Installing symfony/polyfill-ctype (v1.10.0)
 - Warning: symfony/filesystem v4.2.3 requires symfony/polyfill-ctype ~1.8 -> satisfiable by symfony/polyfill-ctype[1.11.x-dev, v1.10.0, v1.8.0, v1.9.0].
 - Installing symfony/filesystem (v4.2.3)
 - Warning: typisttech/image-optimize-command 0.3.1 requires symfony/filesystem ^4.1 -> satisfiable by symfony/filesystem[4.1.x-dev, 4.2.x-dev, 4.3.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.2, v4.2.3].
 - Installing symfony/process (v4.2.3)
 - Warning: spatie/image-optimizer 1.1.5 requires symfony/process ^4.2 -> satisfiable by symfony/process[4.2.x-dev, 4.3.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.2, v4.2.3].
 - Installing psr/log (1.1.0)
 - Warning: typisttech/image-optimize-command 0.3.1 requires psr/log ^1.0 -> satisfiable by psr/log[1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.x-dev].
 - Installing spatie/image-optimizer (1.1.5)
 - Warning: typisttech/image-optimize-command 0.3.1 requires spatie/image-optimizer ^1.1.3 -> satisfiable by spatie/image-optimizer[1.1.3, 1.1.4, 1.1.5].
 - Installing typisttech/image-optimize-command (0.3.1)
Writing lock file
Generating autoload files
---
Success: Package installed.

```

**Comment by TangRufus** [comment]
Although I see `Installing symfony/process (v4.2.3)`, can you confirm `symfony/process v4.2.3` is loaded?

Related:
 - https://github.com/spatie/image-optimizer/issues/82
 - https://github.com/spatie/image-optimizer/commit/83cbef0969df3b6788520aa0d3a3685d83b8bfd0#diff-b00ecbef43b571343ac6639739b14f72

**Comment by opicron** [comment]
I am unsure how to check if the symfone/process is loaded. However checking the /vendor/symfony/process/ path the php scripts are installed.

Running the install command an second time gives no warnings or errors. I assume the correct version is installed.

**Comment by opicron** [comment]
I manually downloaded symfony/process 4.2.3 and the command now works perfect.

**Comment by opicron** [comment]
When I undo the last patch and replace:

`        $process =  Process::fromShellCommandline($command);`

With:

`        $process = new Process($command);`

The script works again..

**Comment by eboy79** [comment]
thank you opicron! 
$process = new Process($command);

**Comment by yavane** [comment]
This is still a valid error :(

But can be fixed with changes from above.

**Comment by Redjam** [comment]
Error is still valid. The fix proposed by @opicron works well. Is it possible du push it in the branch for future users?

**Comment by jbonlinea** [comment]
Hi guys

I bumped into the same error as you 

could you please detail what changes have you made  ? 

> When I undo the last patch and replace:
> 
> ` $process = Process::fromShellCommandline($command);`
> 
> With:
> 
> ` $process = new Process($command);`
> 
> The script works again..

what last patch, and what file have you edited ? 

Thank's

**Comment by Soullighter** [comment]
I hade same error, after replace with @opicron  suggestions everything is working fine
Thank you @jbonlinea for directing us to the file 👍

**Comment by TangRufus** [comment]
Which version you installed?
Is it https://github.com/TypistTech/image-optimize-command/commit/482d9c975b40d8f832f2bb7d82a717e264721d16 ?

**Comment by Soullighter** [comment]
> Which version you installed?
> Is it [482d9c9](https://github.com/TypistTech/image-optimize-command/commit/482d9c975b40d8f832f2bb7d82a717e264721d16) ?

You mean on composer.json?
How to check version?

**Comment by TangRufus** [comment]
Finally found the issue - [wp cli phar _bundles_ `symfony/process` v2](https://github.com/wp-cli/wp-cli/blob/bc37f66e25b9992813b0c50b933aefbf88718e6a/composer.lock#L2794-L2795) which got loaded no matter which we versions specificed in our (and our dependencies') [composer.json](https://github.com/spatie/image-optimizer/blob/5f488115e2ca9411315b2b46662eb916bdbf5c9b/composer.json#L22).

Solution to be investigated. Leave a comment if you have any suggestion.

**Comment by TangRufus** [comment]
more info:

```
wp shell

wp> $reflector = new \ReflectionClass('Symfony\Component\Process\Process');
=> object(ReflectionClass)#2801 (1) {
  ["name"]=>
  string(33) "Symfony\Component\Process\Process"
}
wp> echo $reflector->getFileName();
phar:///usr/bin/wp/vendor/symfony/process/Process.php
wp>
```

**Comment by TangRufus** [comment]
Solution found: Install wp cli via `composer` instead of phar.

This is because phar bundles with `symfony/process` v2 and v2 is always loaded (even though a newer version of it is installed).

[Using `composer` resolve the issue](https://github.com/ItinerisLtd/trellis_install_wp_cli_via_composer#the-solution).

For those using Trellis, check out https://github.com/ItinerisLtd/trellis_install_wp_cli_via_composer

Re-open this issue if you have a better solution.

**Comment by rob** [comment]
This is annoying every single time I install and need to update this file manually.. You could of added a check to run `$process = new Process($command);` or `$process = Process::fromShellCommandline($command);` depending on how it was installed and this would of went away.

**Comment by TangRufus** [comment]
`spatie/image-optimizer` [requires](
https://github.com/spatie/image-optimizer/blob/48f71b968f2764eca8f4885a8a5401d61e920ba8/composer.json#L22) `symfony/process ^4.2|^5.0`.

WP CLI bundle [installs](https://github.com/wp-cli/wp-cli-bundle/blob/3c417a9ef9b3410ddd6d3db38b5d5279b87578e9/composer.lock#L1204-L1205) symfony/process v2.8.52.

Conclusion: WP CLI bundle won't work. Install WP CLI via composer instead.

**Comment by ibrahimhajjaj** [comment]
> When I undo the last patch and replace:
> 
> ` $process = Process::fromShellCommandline($command);`
> 
> With:
> 
> ` $process = new Process($command);`
> 
> The script works again..

Step by step for others who don't know 

nano /root/.wp-cli/packages/vendor/spatie/image-optimizer/src/OptimizerChain.php
CTRL + W and paste this Process::fromShellCommandline($command) and press enter 
changer it with new Process($command)

**Comment by tangrufus** [comment]
Don't do that. 
Install WP CLI via composer instead. See: [requirements](https://github.com/TypistTech/image-optimize-command#requirements)

**Comment by ibrahimhajjaj** [comment]
> Don't do that.
> Install WP CLI via composer instead. See: [requirements](https://github.com/TypistTech/image-optimize-command#requirements)

I've tried that but didn't fix the problem for me.

**Comment by tangrufus** [comment]
Editing vendor code won't work neither.

Send bug report if you are facing the same issue with wp cli installed via composer.
