### ISSUE TITLE
PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\RuntimeException: The process has been signaled with signal "11".

### ISSUE THREAD

**Issue by Redjam** [TypistTech/image-optimize-command#40]
Hi there,

I have a new error. 

`PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\RuntimeException: The process has been signaled with signal "11". in phar:///usr/local/bin/wp/vendor/symfony/process/Process.php:366`

At beginning the script was working well but since 2 days I get this error. I tried to empty composer cache, restart server, but it didn't work. 

Do you know where this issue might comes from?

Many thanks in advance.

**Comment by TangRufus** [comment]
Maybe related to #37

**Comment by TangRufus** [comment]
Can you try:
- install wp cli via `composer`, and 
- install the latest version of image-optimize-command?

**Comment by TangRufus** [comment]
Close due to inactivity. Re-open if the problem persists.
Thanks everyone!
