### ISSUE TITLE
How to delete backup images

### ISSUE THREAD

**Issue by ibrahimhajjaj** [TypistTech/image-optimize-command#466]
Hi, 

Is there are any way to delete backup images... 

I used this command to compress images

`$ wp media regenerate
$ wp image-optimize batch --limit=9999999`

**Comment by tangrufus** [comment]
⚠️ The optimzation is lossy. If you skip backing up the original files, there is no way to recover the original files. Proceed with caution.

After backing up, the original file names are suffixed with [`.original`](https://github.com/TypistTech/image-optimize-command/blob/84e73c59f59a17eff69a39fdaa5295d1888b67c1/src/Operations/Backup.php#L16). You can search them via the file name `*.original`.

See: https://github.com/TypistTech/image-optimize-command#how-to-skip-backups--restorations
