### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by italianrich** [TypistTech/image-optimize-command#472]
Hi,
When installing this tool via "wp package install typisttech/image-optimize-command:@stable" I get this error message:

Error: curl error 60 while downloading https://wp-cli.org/package-index/packages.json: SSL certificate problem: certificate has expired

Please update your certificate and/or provide a workaround for install.

Have a great day,
Richard

**Comment by tangrufus** [comment]
> Essentially, you likely have an out of date SSL certificate on your machine that you'll need to update.
>
> -- https://github.com/wp-cli/package-command/issues/145#issuecomment-1219660532

See: 
 - https://github.com/wp-cli/package-command/issues/145
 - https://github.com/wp-cli/profile-command/issues/172

**Comment by italianrich** [comment]
Many thanks!

**Comment by italianrich** [comment]
using php -i | grep curl I found the location of the Certificate Authority bundles:
CURL_CA_BUNDLE => /opt/bitnami/common/openssl/certs/curl-ca-bundle.crt
SSL_CERT_FILE => /opt/bitnami/common/openssl/certs/curl-ca-bundle.crt

I updated the curl-ca-bundle.crt file like so (after backing up the bundle first)
sudo curl https://curl.se/ca/cacert.pem -o /etc/pki/tls/certs/ca-bundle.crt -k
the command "wp package install typisttech/image-optimize-command:https://github.com/stable" completed fine after that
