### ISSUE TITLE
Skip backup file

### ISSUE THREAD

**Issue by ciarlystreet** [TypistTech/image-optimize-command#73]
Hi,
It's possible to skip the backup file when executing the 'wp image-optimize attachment' command?

**Comment by TangRufus** [comment]
Not in current version. Will you able to create a pull request?

Note to anyone wants to skip backup:
The original images will be gone forever

**Comment by ciarlystreet** [comment]
> Not in current version. Will you able to create a pull request?
> 
> Note to anyone wants to skip backup:
> The original images will be gone forever

Hi TangRufus,
i created the pull request #78
